### ISSUE TITLE
Worker cleanup mechanism

### ISSUE THREAD

**Issue by fkorotkov** [cirruslabs/cirrus-cli#248]
Right now it's possible to let a Parallel VM hanging after a panic, bug or some other issue when CLI exited unpredictably. One possible solution is to add a self healing mechanism where UUIDs for the VMs can be generated in a way to indicate that it was created by this worker and then the worker can periodically list VMs and find such hanging VMs and remove them.

@edigaryev what do you think about it?

**Comment by edigaryev** [comment]
Good idea, we could use [version 1 UUID's](https://en.wikipedia.org/wiki/Universally_unique_identifier#Version_1_(date-time_and_MAC_address)) with our magic number specified instead of a real MAC-address.

However, CLI codepath that [clones non-suspended VMs](https://github.com/cirruslabs/cirrus-cli/blob/b1427f9b3bdba0a6db93b367aab4e15826c377d9/internal/executor/instance/persistentworker/isolation/parallels/vm.go#L60) uses `prlctl clone` command, which doesn't have a `--uuid` argument.

On top of that, simply removing the VM based on it's UUID properties (and maybe it's state) seems like a bad idea b.c. it might cause races.

A more robust mechanism is perhaps to implement something like a watchdog that periodically touches VMs started by the specific persistent worker instance. VMs that are not touched for a specific period of time can then be safely removed.

However, Parallels doesn't support labels, and if we're going to store the timestamp in the VM's description — then there's a problem when event a VM's description can't be edited in suspended state, which is weird.

We can, of course, set the description after we clone the VM, but this still leaves some race window.

But I can implement a hybrid method, where the timestamp is stored either in the VM's name or it's UUID depending on the initial state of the base VM.

@fkorotkov what do you think?

**Comment by fkorotkov** [comment]
Can we use the `NEW_NAME` for clone?

> clone <ID | NAME> --name <NEW_NAME>

There is also `--regenerate-src-uuid` flag but I'm not sure what it does 🤔

**Comment by edigaryev** [comment]
> Can we use the `NEW_NAME` for clone?

Yes:

>But I can implement a hybrid method, where the timestamp is stored either in the **VM's name** or it's UUID depending on the initial state of the base VM.

>There is also `--regenerate-src-uuid` flag but I'm not sure what it does 🤔

Looks like some [SMBIOS-related identifier](https://download.parallels.com/desktop/v13/docs/en_US/Parallels%20Desktop%20Pro%20Edition%20Command-Line%20Reference/23457.htm), but whatever it is — it has no argument that we can specify.

**Comment by fkorotkov** [comment]
My idea was to have a UUID with some structure like it always starts with `ci` then there can be a small hash from the worker name (in case there are several workers on one host) and the rest is some random stuff or simply task ID. For example, something like `ci-cofefe-123456789` where `cofefe` is a hash or base64 of the worker name.

This way a worker can identify by prefix that it owns this VM and check if task id is one of the running tasks and not a zombi VM.

**Comment by fkorotkov** [comment]
I think we should prioritize it since I saw some hanging VMs on the persistent workers. Before starting a VM the CLI can list the vms and remove all vms which starts with `ci-cofefe-` prefix.

**Comment by fkorotkov** [comment]
It seems there is also an issue that these zombie VMs are reused for cloning. See https://github.com/flutter/plugins/pull/3514#issuecomment-773678099. I'm not quite sure how it's happening though. Looking it right now.

**Comment by edigaryev** [comment]
It seems that the proper cleanup sequence in the https://github.com/cirruslabs/cirrus-cli/pull/278 actually resolved the underlying cause.
