### ISSUE TITLE
Support other platforms for Parallels isolation

### ISSUE THREAD

**Issue by fkorotkov** [cirruslabs/cirrus-cli#253]
Right now only `darwin` platform is supported. It will be great to close the loop and support Linux and Windows VMs as well.

**Comment by edigaryev** [comment]
Any idea how we're going to SSH into Windows and also do this (which is somewhat distro-specific because there are many `NTP` implementations)? 🤔 

https://github.com/cirruslabs/cirrus-cli/blob/6ce9f6b2ed22b9df0d4c4c1f27abae9db226efdf/internal/executor/instance/persistentworker/isolation/parallels/parallels.go#L106-L109

**Comment by fkorotkov** [comment]
If Packer builder supports any Windows host then we should check how it's doing it. 🤔 Anyways, created the issue for tracking. It's not a priority but worth investigating once bandwidth allows.
