### ISSUE TITLE
#181 causes bad ux

### ISSUE THREAD

**Issue by AstraLuma** [cirruslabs/cirrus-cli#290]
#181 causes bad UX because the default configuration differs in behavior from the cloud version, and the resulting errors may not be obvious as to why.

Yeah, having a user-facing knob for this is good and useful. But given that there's no time-based limits on image checking, pulling every run is reasonable. (At least, once per run if the image is used in multiple places.)

**Comment by fkorotkov** [comment]
Agreed that it's not good UX that cloud behavior is different. We introduced it since we saw rate limits in CI and locally since CLI's integration tests are running a lot of tasks locally. Maybe we can switch the default to always pull and override it in integration tests.

@edigaryev, @AstraLuma what do you both think?

**Comment by AstraLuma** [comment]
My usual design sensibility is to make the default the most reasonable/most expected/least surprising option.

In this case, "Oh, I haven't pulled `python:3` in a while and now my pipelines are failing in weird ways because they're on 3.8 instead of 3.9" (the inspiration for filing this issue) is weird, surprising, and (if you're not an expert in the ecosystem) difficult to debug.

Yes, the option should be there, for things like "oh yeah, I have my own pull policy" (eg, once a day on a cron job) or other specialized cases. `--help` should be useful.

**Comment by fkorotkov** [comment]
This will be fixed with the new release that we are about to tag.
