### ISSUE TITLE
Validate top level declarations

### ISSUE THREAD

**Issue by fkorotkov** [cirruslabs/cirrus-cli#329]
While parsing things CLI should validate that all top level declaration in a YAML file are either a task-like or a YAML node with a name of a collectible field.

For example, it will catch issues when new users use `task_foo` syntax instead of `foo_task`.

**Comment by edigaryev** [comment]
> all top level declaration in a YAML file are either a task-like or a YAML node with a name of a collectible field

> For example, it will catch issues when new users use `task_foo` syntax instead of `foo_task`.

This heuristic doesn't seem to work in this case:

```yaml
task_foo:
  env:
    A: B
```

Possible solutions:

* we could assign a "reference counter" to the root-level nodes and find out which ones are never used (including YAML aliases usage), but I'm not sure this is a good idea, because it makes the parser very opinionated (just like the Go language treats unused imports and variables), and that might annoy a lot of people who like to tinker with their configuration often

* we could also try to match root-level nodes by `task_*` mask and generate errors, but that might prone to potential false-positives

But overall it seems that we will need to support emitting `warning`-level issues from the parser to move forward confidently with this.

@fkorotkov what do you think?

**Comment by fkorotkov** [comment]
Yeah, since you implemented the rich error reporting in the UI, I think just having warnings will work perfectly.

Good point about the anchors. I initially thought just to check if a node matches any collectible field of the parsers. But now I recall that I've seen people grouping all the aliases in under one `aliases` node. 🤔 

In the meantime I've seen several different people using `task_foo` syntax. Maybe we should just complain about this exact pattern? 🤔
