### ISSUE TITLE
YAML: Inherited matrix is not being reduced in new task

### ISSUE THREAD

**Issue by edsantiago** [cirruslabs/cirrus-cli#530]
We have a hairy CI setup with a reusable `matrix` that defines three platforms on which to run:
https://github.com/containers/podman/blob/5cba4dc2e490b5c652ba0821067b63d7b2e4cf8f/.cirrus.yml#L158-L173

This is reused in a subsequent rule, but with the `matrix` collapsed into just one platform:
https://github.com/containers/podman/blob/5cba4dc2e490b5c652ba0821067b63d7b2e4cf8f/.cirrus.yml#L617-L632

The collapse isn't happening. Instead, three independent `fedora-36` jobs are triggering and running. This is best seen in the screen capture here: https://github.com/containers/podman/issues/14623 (note the triple identical fedora-36 lines).

I've tried two different approaches to solving it: [removing 'matrix'](https://github.com/containers/podman/pull/14624) and [removing a possibly-extra field from matrix](https://github.com/containers/podman/pull/14629).

/cc @cevich

**Comment by edigaryev** [comment]
Hello Ed!

There's an existing behavior where `env:` maps get merged together instead of overwritten: this way defining `env:` in YAML's root level works and allows for finer customization in tasks. The same applies for defining `env:` multiple times on the same level, like this:

```yaml
task:
  env:
    ARCH: arm64
  matrix:
    - env:
        OS: linux
    - env:
        OS: darwin

```

This will result in two tasks, one with `ARCH=arm64 OS=linux` and the other with `ARCH=arm64 OS=darwin`.

Regarding your specific case, I see two solutions:

1. Remove `matrix: *platform_axis` from the `local_system_test_task` and specify the list of platforms manually in each depending task.
2. Use the rules of the YAML spec [w.r.t. map merging](https://yaml.org/type/merge.html) to prevent the `matrix:` from being copied from the `local_system_test_task`

I've created a solution for #2 in https://github.com/containers/podman/pull/14637, so closing this, assuming that this solution will work for you.
