### ISSUE TITLE
Waiting on `cirrus worker pause` not always working

### ISSUE THREAD

**Issue by fkorotkov** [cirruslabs/cirrus-cli#649]
It seems where there is a long running task on the worker the logic is not quite working.

Need to investigate what's going on there.

**Comment by edigaryev** [comment]
My guess is that this happens due to [ridiculously large per-call timout](https://github.com/cirruslabs/cirrus-cli/blob/91e894ec174432581593b4550e5d5f2ae31e3ca9/internal/worker/upstream/upstream.go#L29) we have in Persistent Workers for communicating with RPC.

Would be nice to get some more evidence/logs, e.g. that it takes around 15 minutes for the timeout to happen in Ansible.
